In [5]:
# importing libraries
import numpy as np
import matplotlib.pyplot as plt

In [9]:
# 1. Create a 1D array of numbers from 0 to 9.
arr = np.arange(0,9)
print(arr)

[0 1 2 3 4 5 6 7 8]


In [13]:
# 2. Create a 3×3 numpy array of all True’s
three_arr =np.ones((3,3))
print('Original Array : \n',three_arr)
three_arr >0


Original Array : 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [14]:
# 3. Given an array as input, print only odd numbers as output
arr1=np.array([1,2,3,4,5,6,7,8,9])
print("Array with odd numbers: ",arr1[arr1%2!=0])

Array with odd numbers:  [1 3 5 7 9]


In [15]:
# 4. Replace all odd numbers in arr with -2
arr1=np.array([1,2,3,4,5,6,7,8,9])
print("Original Array:",arr1)
print("Replacing odd numbers in arr1 with -2:")
arr1[arr1%2!=0]=-2
arr1

Original Array: [1 2 3 4 5 6 7 8 9]
Replacing odd numbers in arr1 with -2:


array([-2,  2, -2,  4, -2,  6, -2,  8, -2])

In [18]:
# 5. How to reshape an array?
arr2=np.array([[2,4],[6,8],[5,10]])
print(arr2,arr2.shape)

[[ 2  4]
 [ 6  8]
 [ 5 10]] (3, 2)


In [20]:
# 6. Convert a 1D array to a 2D array with 2 rows
arr3=np.arange(10)
print("original 1D array")
arr3

print("\n Reshaped 2D array ")
arr4=arr3.reshape(2,5)
arr4

original 1D array

 Reshaped 2D array 


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [23]:
# 7. Given an array  a  = [1,2,3,4,5,6,7,8,9] , create  new array b from a such that b includes all odd numbers and 4 multiples.
import numpy as np
a=np.arange(1,10)
print("original array:",a)
b=a[np.where((a%2!=0)|(a%4==0))]
print("modified array:",b)

original array: [1 2 3 4 5 6 7 8 9]
modified array: [1 3 4 5 7 8 9]


In [28]:
# 8. Given array, check if there are any null values and print them out.
a =np.array([0,1,2,3,4,0,0,6,7,8,9])
b=np.append(a,np.NaN)
print(b)

c=b[np.isnan(b)]
c


[ 0.  1.  2.  3.  4.  0.  0.  6.  7.  8.  9. nan]


array([nan])

In [29]:
# 9. How to replace all missing values with 0 in a numpy array?
c=np.isnan((b))
d=np.where((c))
b[d]=0
b

array([0., 1., 2., 3., 4., 0., 0., 6., 7., 8., 9., 0.])

In [30]:
# 10. How to find the count of each unique number in a NumPy array?
k=np.array([1,2,3,2,1,5,6,5,4,5,3,7])
unique_values,unique_counts=np.unique(a, return_counts=True)
unique_values,unique_counts

(array([0, 1, 2, 3, 4, 6, 7, 8, 9]),
 array([3, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int64))

In [35]:
# 11. How to convert a numeric to a categorical (text) array?
favourite_muscians ={1:'Ilayaraja',2:'ARRahman',3:'Pritam',4:'Amittrivedi'}
txt_favourite_muscians=[]
for i in favourite_muscians:
    txt_favourite_muscians =np.append(txt_favourite_muscians,favourite_muscians[i])
txt_favourite_muscians

array(['Ilayaraja', 'ARRahman', 'Pritam', 'Amittrivedi'], dtype='<U32')

In [40]:
# 12. Write a program to print all numbers between 99 and 299 which are either divisible by 5 or 7. Exclude the elements which are divisible by both. 
e=np.arange(99,300)
print("original array:\n")


original array:



In [41]:
e 
f=e[(e%5==0)|(e%7==0)]  
f

array([100, 105, 110, 112, 115, 119, 120, 125, 126, 130, 133, 135, 140,
       145, 147, 150, 154, 155, 160, 161, 165, 168, 170, 175, 180, 182,
       185, 189, 190, 195, 196, 200, 203, 205, 210, 215, 217, 220, 224,
       225, 230, 231, 235, 238, 240, 245, 250, 252, 255, 259, 260, 265,
       266, 270, 273, 275, 280, 285, 287, 290, 294, 295])

In [42]:
g =f[np.where((f%5!=0)|(f%7!=0))]
print(" Final array excluding common elements:\n")
g

 Final array excluding common elements:



array([100, 110, 112, 115, 119, 120, 125, 126, 130, 133, 135, 145, 147,
       150, 154, 155, 160, 161, 165, 168, 170, 180, 182, 185, 189, 190,
       195, 196, 200, 203, 205, 215, 217, 220, 224, 225, 230, 231, 235,
       238, 240, 250, 252, 255, 259, 260, 265, 266, 270, 273, 275, 285,
       287, 290, 294, 295])

In [45]:
# 13. Write a program to reverse an array and print (Don’t use inbuilt reverse functions)

orginal_arr=np.arange(8)
print("Original array \n")
orginal_arr

Original array 



array([0, 1, 2, 3, 4, 5, 6, 7])

In [46]:
reverse_arr=arr[::-1]
print(" Reverse array \n")
reverse_arr

 Reversed array 



array([8, 7, 6, 5, 4, 3, 2, 1, 0])

# The End